Compose env vars
grafana/oats pull request #27
Opened 2023-10-04 16:28 UTC by matt-hensley

2023-10-04 18:26 UTC, MattFrick approved these changes
Thanks, this adds so much functionality!
Eventually we should be able to remove the template parsing.
I also wonder if creating a single generated config that would "include" the template and regular docker-compose file(s) might be simpler.

2023-10-06 09:56 UTC, zeitlinger requested changes

2023-10-06 09:56 UTC, zeitlinger commented on yaml/model.go
> +	Environment         []string            `yaml:"environment"`
```suggestion
	Environment         []string            `yaml:"env"`
```

2023-10-06 09:56 UTC, zeitlinger commented on yaml/model.go
> +	Environment         []string            `yaml:"environment"`
`env` matches k8s pods

2023-10-06 09:56 UTC, zeitlinger commented on yaml/generator.go
> +		env = append(env, "OATS_"+strings.ToUpper(k)+"="+v.(string))
```suggestion
		env = append(env, k+"="+v.(string))
```

2023-10-06 09:56 UTC, zeitlinger commented on yaml/generator.go
> +		env = append(env, "OATS_"+strings.ToUpper(k)+"="+v.(string))
prepend OATS_ and make upper case in all usages - that makes it easier to follow

2023-10-06 09:56 UTC, zeitlinger commented on yaml/generator.go
> +		env = append(env, "OATS_"+v)
```suggestion
		env = append(env, k+"="+v)
```

2023-10-06 09:56 UTC, zeitlinger commented on yaml/generator.go
> +		env = append(env, "OATS_"+v)
we also may want to pass in environment variables to the application directly, so prepending OATS_ won't work.

2023-10-06 16:03 UTC, MattFrick commented
> we also may want to pass in environment variables to the application directly, so prepending OATS_ won't work.
Is that case something like when a (Java) generator wants to set an env var that is also used outside of oats, so it can't have its own unique, oats-prefixed name?
If we don't generally prepend OATS_, could we maybe change the name of ConfigDir to OatsConfigDir?  That one in particular strikes me as really vague and other things might use the env var CONFIGDIR.

2023-10-19 19:55 UTC, grcevski approved these changes
LGTM!

2023-10-19 20:06 UTC, zeitlinger approved these changes

2023-10-19 21:01 UTC, merged